BEGIN;

CREATE TABLE IF NOT EXISTS payment_details (
	id BIGSERIAL PRIMARY KEY,
	payment_id BIGSERIAL NOT NULL,
	name VARCHAR(50) NOT NULL,
	phone VARCHAR(15),
	email VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (payment_id) REFERENCES payments(id)
);

COMMIT;
